#!/usr/bin/env python3
"""Generate sdk/board/<board>/boardinfo files.

One sourceable KEY=VALUE file per board directory, in the style the
Cadmium installer uses, derived from data the tree already carries:

  BOARD    the board directory name
  FAMILY   the SoC-family directory whose common.config the board
           includes (itself for arch boards and family-only boards)
  SOC      the family name's SoC part
  ARCH     from the arch fragment the board's include chain reaches
  BOOTFW   how this board boots, by family (depthcharge / uefi / uboot /
           abl) - the same classification system-install detects at run
           time, recorded here so tooling can know it offline
  DTS      the kernel devicetree name, when the board pins one

Run from the repo root; rewrites every boardinfo. Idempotent, so the
files stay mechanical - edit THIS script, not the outputs.
"""

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
BOARDS = ROOT / "sdk" / "board"

BOOTFW_BY_FAMILY_PREFIX = [
    ("chromebook-", "depthcharge"),
    ("qualcomm-", "abl"),
    ("apple-", "uefi"),      # m1n1 + u-boot present a UEFI-ish path
    ("steamdeck", "uefi"),
    ("x86_64", "uefi"),
    ("arm64", "uefi"),
    ("retroid-", "abl"),
    ("allwinner-", "uboot"),
    ("amlogic-", "uboot"),
    ("rockchip-", "uboot"),
]


def read(p: Path) -> str:
    try:
        return p.read_text()
    except OSError:
        return ""


def family_of(board: Path) -> str:
    cfg = read(board / "board.config")
    m = re.search(r"include sdk/board/([a-z0-9._-]+)/common\.config", cfg)
    if m:
        return m.group(1)
    return board.name


def arch_of(board: Path, family: str) -> str:
    # Follow the include chain: board -> family -> grandparent family
    # (the Chromebook families include chromebook-common, which is where
    # BR2_aarch64 lives).
    chain = [board / "board.config", BOARDS / family / "common.config"]
    m = re.search(r"include sdk/board/([a-z0-9._-]+)/common\.config",
                  read(BOARDS / family / "common.config"))
    if m:
        chain.append(BOARDS / m.group(1) / "common.config")
    text = ""
    for p in chain:
        t = read(p)
        text += t
        a = re.search(r"include sdk/defconfig/arch/([a-z0-9_]+)\.config", t)
        if a:
            return a.group(1)
    if board.name in ("x86_64", "arm64"):
        return board.name
    if "BR2_aarch64=y" in text:
        return "arm64"
    if "BR2_arm=y" in text:
        return "armv7"
    if "BR2_x86_64=y" in text or "x86_64" in text:
        return "x86_64"
    return "unknown"


def soc_of(family: str) -> str:
    if family in ("x86_64", "arm64"):
        return "generic"
    if family == "steamdeck":
        return "vangogh"
    if "-" in family:
        return family.split("-", 1)[1]
    return family


def bootfw_of(family: str, board: str) -> str:
    for prefix, fw in BOOTFW_BY_FAMILY_PREFIX:
        if family.startswith(prefix) or board.startswith(prefix):
            return fw
    return "uboot"


def dts_of(board: Path) -> str:
    m = re.search(r'BR2_LINUX_KERNEL_INTREE_DTS_NAME="([^"]+)"',
                  read(board / "board.config"))
    return m.group(1).split()[0] if m else ""


def main() -> int:
    count = 0
    for board in sorted(BOARDS.iterdir()):
        if not board.is_dir() or board.name == "common":
            continue
        if not (board / "board.config").exists() and \
           not (board / "common.config").exists():
            continue
        family = family_of(board)
        lines = [
            "#!/bin/false",
            "# Generated by util/gen-boardinfo.py - edit that, not this.",
            f"BOARD={board.name}",
            f"FAMILY={family}",
            f"SOC={soc_of(family)}",
            f"ARCH={arch_of(board, family)}",
            f"BOOTFW={bootfw_of(family, board.name)}",
        ]
        dts = dts_of(board)
        if dts:
            lines.append(f"DTS={dts}")
        (board / "boardinfo").write_text("\n".join(lines) + "\n")
        count += 1
    print(f"wrote {count} boardinfo files")
    return 0


if __name__ == "__main__":
    sys.exit(main())
