#!/bin/bash
# Generate a CMake toolchain file that cross-compiles C/C++ against a Swift
# Linux SDK sysroot, so CMake projects (SDL games, native libraries) build for
# the image with the same sysroot SwiftPM uses:
#
#     util/make-cmake-toolchain.sh --sdk swift-linux-arm64 -o arm64.cmake
#     cmake -B build -DCMAKE_TOOLCHAIN_FILE=arm64.cmake
#
# The compiler is clang/clang++ (from the Swift toolchain or PATH) driven with
# --target and --sysroot; the portable bundle's sysroot carries the folded
# cross-gcc (crt objects, libgcc, libstdc++), which clang discovers from the
# sysroot alone. lld links.
#
# Usage:
#   util/make-cmake-toolchain.sh --sdk <name|path> [--triple T] [-o FILE]
#   util/make-cmake-toolchain.sh --sysroot DIR --triple T [-o FILE]
#
#   --sdk      installed Swift SDK bundle name (looked up in
#              ~/.swiftpm/swift-sdks) or a path to an .artifactbundle.
#              The sysroot and triple are read from its swift-sdk.json.
#   --triple   target triple (required with --sysroot; with --sdk, selects
#              among a multi-arch bundle's triples, default = its only one).
#   --sysroot  use an explicit sysroot directory instead of a bundle.
#   -o FILE    output path (default: swift-linux-<cpu>.toolchain.cmake)
set -eu

SDK=""; SYSROOT=""; TRIPLE=""; OUT=""
while [ $# -gt 0 ]; do
	case "$1" in
		--sdk) SDK="$2"; shift 2 ;;
		--sysroot) SYSROOT="$2"; shift 2 ;;
		--triple) TRIPLE="$2"; shift 2 ;;
		-o|--out) OUT="$2"; shift 2 ;;
		-h|--help) grep '^#' "$0" | sed 's/^# \?//'; exit 0 ;;
		*) echo "unknown arg: $1" >&2; exit 1 ;;
	esac
done

if [ -n "$SDK" ]; then
	command -v jq >/dev/null || { echo "error: jq is required with --sdk" >&2; exit 1; }
	BUNDLE="$SDK"
	[ -d "$BUNDLE" ] || BUNDLE="$HOME/.swiftpm/swift-sdks/$SDK"
	[ -d "$BUNDLE" ] || BUNDLE="$HOME/.swiftpm/swift-sdks/$SDK.artifactbundle"
	[ -d "$BUNDLE" ] || { echo "error: SDK bundle not found: $SDK" >&2; exit 1; }
	JSON="$(find "$BUNDLE" -maxdepth 2 -name swift-sdk.json | head -1)"
	[ -n "$JSON" ] || { echo "error: no swift-sdk.json in $BUNDLE" >&2; exit 1; }
	if [ -z "$TRIPLE" ]; then
		count=$(jq -r '.targetTriples | length' "$JSON")
		[ "$count" = 1 ] || { echo "error: bundle has $count triples; pick one with --triple:" >&2; jq -r '.targetTriples | keys[]' "$JSON" >&2; exit 1; }
		TRIPLE=$(jq -r '.targetTriples | keys[0]' "$JSON")
	fi
	REL=$(jq -r --arg t "$TRIPLE" '.targetTriples[$t].sdkRootPath // empty' "$JSON")
	[ -n "$REL" ] || { echo "error: triple $TRIPLE not in $JSON" >&2; exit 1; }
	case "$REL" in
		/*) SYSROOT="$REL" ;;                       # local-mode bundle: absolute
		*)  SYSROOT="$(dirname "$JSON")/$REL" ;;    # portable bundle: relative
	esac
fi

[ -n "$SYSROOT" ] && [ -d "$SYSROOT" ] || { echo "error: sysroot not found: ${SYSROOT:-<unset>} (use --sdk or --sysroot)" >&2; exit 1; }
[ -n "$TRIPLE" ] || { echo "error: --triple is required with --sysroot" >&2; exit 1; }
SYSROOT="$(cd "$SYSROOT" && pwd)"
CPU="${TRIPLE%%-*}"

# clang from PATH, or next to swiftc (swiftly toolchains ship clang).
CLANG="${CLANG:-$(command -v clang || true)}"
if [ -z "$CLANG" ] && command -v swiftc >/dev/null; then
	c="$(dirname "$(command -v swiftc)")/clang"
	[ -x "$c" ] && CLANG="$c"
fi
[ -n "$CLANG" ] || { echo "error: clang not found (install LLVM or a Swift toolchain)" >&2; exit 1; }
CLANGXX="${CLANG}++"
[ -x "$CLANGXX" ] || CLANGXX="$(dirname "$CLANG")/clang++"

OUT="${OUT:-swift-linux-$CPU.toolchain.cmake}"
cat > "$OUT" <<EOF
# CMake toolchain for cross-compiling to Swift Linux ($TRIPLE).
# Generated by util/make-cmake-toolchain.sh - regenerate rather than edit.
set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR $CPU)

set(CMAKE_SYSROOT "$SYSROOT")

set(CMAKE_C_COMPILER "$CLANG")
set(CMAKE_CXX_COMPILER "$CLANGXX")
set(CMAKE_ASM_COMPILER "$CLANG")
set(CMAKE_C_COMPILER_TARGET $TRIPLE)
set(CMAKE_CXX_COMPILER_TARGET $TRIPLE)
set(CMAKE_ASM_COMPILER_TARGET $TRIPLE)

# lld links; the sysroot's folded cross-gcc provides crt/libgcc/libstdc++.
set(CMAKE_EXE_LINKER_FLAGS_INIT "-fuse-ld=lld")
set(CMAKE_SHARED_LINKER_FLAGS_INIT "-fuse-ld=lld")
set(CMAKE_MODULE_LINKER_FLAGS_INIT "-fuse-ld=lld")

# Search only the sysroot for headers/libs/packages; never for host programs.
set(CMAKE_FIND_ROOT_PATH "$SYSROOT")
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)

# pkg-config against the sysroot only.
set(ENV{PKG_CONFIG_SYSROOT_DIR} "$SYSROOT")
set(ENV{PKG_CONFIG_LIBDIR} "$SYSROOT/usr/lib/pkgconfig:$SYSROOT/usr/share/pkgconfig")
EOF

echo "toolchain : $OUT"
echo "triple    : $TRIPLE"
echo "sysroot   : $SYSROOT"
echo "clang     : $CLANG"
